---
- name: Setup Pihole.
  hosts: all
  become: true

  pre_tasks:
    - name: Load configuration variables (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yaml
        - config.yaml

    - name: Update cache and upgrade packages.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full

    - name: Set DNSStubListener to no.
      ansible.builtin.lineinfile:
        search_string: '#DNSStubListener='
        line: 'DNSStubListener=no'
        path: '/etc/systemd/resolved.conf'

    - name: Remove resolv.conf, if present (Ubuntu).
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release'] | int >= 17

    - name: Create a symbolic link for resolv.conf (Ubuntu).
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
      when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release'] | int >= 17

    - name: Restart systemd-resolved (Ubuntu).
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
      when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release'] | int >= 17

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.ansible.yaml

  tasks:
#    - name: Setup Docker.
#      ansible.builtin.import_tasks: tasks/docker.ansible.yaml

#    - name: Setup Pihole.
#      ansible.builtin.import_tasks: tasks/pihole.ansible.yaml

#    - name: Setup keepalived.
#      ansible.builtin.import_tasks: tasks/keepalived.ansible.yaml

    - name: Setup sync.
      ansible.builtin.import_tasks: tasks/sync.ansible.yaml
