---
- name: Install Docker and Docker-Compose.
  ansible.builtin.apt:
    name:
      - docker
      - docker-compose
    state: present

# Raspbian sometimes requires a restart in order to enable docker after applying updates.
# If you know of a better way to detect Raspbian, please submit a PR.
- name: Restart server if it's Raspbian
  ansible.builtin.reboot:
  when: ansible_facts['architecture'] == "aarch64"

- name: Ensure Docker is started.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add the ansible user to the Docker group.
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset connection to remote server to use docker group.
  ansible.builtin.meta: reset_connection
